apiVersion: v1
kind: ConfigMap
metadata:
  name: etl-config
  namespace: etl
data:
  DB_PATH: "/data/app.db"
  COUNTRIES_API_URL: "https://restcountries.com/v3.1/all?fields=name,cca2,region,population,capital"
